"""added aptitude 4

Revision ID: acb3aba6eb8f
Revises: 69b0e7be77e3
Create Date: 2025-09-17 22:38:17.991668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb3aba6eb8f'
down_revision: Union[str, Sequence[str], None] = '69b0e7be77e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aptitude_questions', sa.Column('field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aptitude_questions', 'field')
    # ### end Alembic commands ###
