"""added career questions 3

Revision ID: bedc3ab355b9
Revises: 8d9b5be00570
Create Date: 2025-09-18 01:09:08.632776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedc3ab355b9'
down_revision: Union[str, Sequence[str], None] = '8d9b5be00570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('sub_category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'sub_category')
    # ### end Alembic commands ###
